// SPDX-FileCopyrightText: AdGuard Software Limited
//
// SPDX-License-Identifier: GPL-3.0-or-later

export const langsMap = {
    ru: 'Русский',
    en: 'English',
    de: 'Deutsch',
    ja: '日本語',
    nl: 'Nederlands',
    es: 'Español',
    pt: 'Português',
    tr: 'Türkçe',
    fr: 'Français',
    id: 'Bahasa Indonesia',
    bg: 'Български',
    zh: '中文',
    cs: 'Český',
    sk: 'Slovenčina',
    he: 'עברית',
    it: 'Italiano',
    lv: 'Latviešu',
    lt: 'Lietuvių',
    ar: 'اَلْعَرَبِيَّةُ',
    ro: 'Română',
    fi: 'Suomi',
    pl: 'Polski',
    is: 'Íslenska',
    no: 'Norsk',
    el: 'Ελληνικά',
    cz: 'Čeština',
    hu: 'Magyar',
    da: 'Dansk',
    vi: 'Tiếng Việt',
    et: 'Eesti',
    fa: 'فارسی',
    sv: 'Svenska',
    ko: '한국어',
    fo: 'Føroyskt',
    th: 'ไทย',
    sr: 'Српски',
    hr: 'Hrvatski',
    hi: 'हिन्दी',
    uk: 'Українська',
    tg: 'Тоҷикӣ',
    ps: 'پښتو',
    mk: 'Македонски',
};
