# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: BFP
  name: Build for standalone deploy
  description: Prepare standalone build for publish

stages:
- Build for publish:
    manual: false
    final: false
    jobs:
    - Build for publish
- Deploy for Test to Slack QA:
    manual: false
    final: false
    jobs:
    - Deploy to Slack for Publish
- Git Tagging:
    manual: false
    final: false
    jobs:
    - Git Tagging


Build for publish:
  key: JOB1
  other:
    clean-working-dir: true
  tasks:
  - checkout: !include common/checkout-default-repo.yaml
  - checkout:
      repository: sciter-adguard-mini-private
      path: adguard-mini-private
      force-clean-build: 'true'
      description: Checkout Default Repository
  - checkout:
      repository: slack-scripts
      path: slack-scripts
      force-clean-build: 'true'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - bamboo-specs/scripts/prebuild_vars.sh
      working-dir: main
      description: Obtaining Prebuild Vars
  - inject-variables:
      file: main/build/vars.txt
      scope: RESULT
      namespace: inject
      description: Inject prebuild vars
  - script:
      interpreter: SHELL
      scripts:
      - ./bamboo-specs/scripts/configure.sh
      working-dir: main
      description: Configure
  - script:
      interpreter: SHELL
      scripts:
      - ./bamboo-specs/scripts/build.sh ${bamboo.build.config}
      working-dir: main
      description: Build app
  - inject-variables:
      file: main/build/${bamboo.build.config}/version.txt
      scope: RESULT
      namespace: inject
      description: Inject version
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash

        set -e

        source .venv/bin/activate

        BUILD_DIR="../../build/${bamboo.build.config}"

        python -u Support/Scripts/changelog.py \
            --repo="SCITER/adguard-mini" \
            --gh-repo="AdguardTeam/AdGuardForSafari" \
            --output="$BUILD_DIR" \
            --channel="${bamboo.update.channel}" \
            --version="${bamboo.inject.base_version_name}" \
            --from=${bamboo.inject.tag_from}
      working-dir: main
      description: Create changelog
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash

        set -x

        ./bamboo-specs/scripts/generate_appcast.sh
      working-dir: main
      description: Create appcast
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash

        set -e

        bundle exec fastlane to_sentry config:${bamboo.build.config}
      working-dir: main
      description: Upload dSYMs to Sentry
  artifacts: !include build-for-publish-plans/artifacts-standalone.yaml
  requirements: !include common/build-requirements.yaml
  artifact-subscriptions: []

Deploy to Slack for Publish:
  key: DTSFP
  other:
    clean-working-dir: true
  tasks:
  - checkout:
      repository: slack-scripts
      force-clean-build: 'false'
      description: Checkout Default Repository
  - checkout:
      repository: sciter-adguard-mini
      path: main
      force-clean-build: 'false'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - ./main/bamboo-specs/scripts/publish_to_slack.sh "${PWD}/slack_kit.py" "${PWD}/build/${bamboo.build.config}"
      description: Deploy to Slack
  requirements: !include common/build-requirements.yaml
  artifact-subscriptions:
  - artifact: !include common/app-archive-name.yaml
    destination: build/${bamboo.build.config}
  - artifact: build.json
    destination: build/${bamboo.build.config}
  - artifact: changelog.md
    destination: build/${bamboo.build.config}

Git Tagging:
  key: AGMINIBFPGT
  other:
    clean-working-dir: true
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Default Repository
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
      configuration:
        selectedRepository: defaultRepository
        tagName: v${bamboo.inject.version_name}
  requirements: !include common/build-requirements.yaml

variables:
  build.config: Nightly
  changelog.tag.from: latest@tag
  update.channel: nightly
repositories:
- sciter-adguard-mini:
    scope: global
- sciter-adguard-mini-private:
    scope: global
- slack-scripts:
    scope: global

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
- events:
  - plan-failed
  recipients:
  - webhook:
      name: Build webhook
      url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-mini-deploy
labels: []
other:
  concurrent-build-plugin: system-default

branch-overrides:
- beta:
   triggers: []
   variables:
     build.config: Beta
     changelog.tag.from: latest@tag
     update.channel: beta
- release:
    triggers: []
    variables:
      build.config: Release
      changelog.tag.from: latest@tag
      update.channel: release
