# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: BFM
  name: Build for MAS deploy

stages:
- Build for MAS:
    manual: false
    final: false
    jobs:
    - Build
- Publish to Slack:
    manual: false
    final: false
    jobs:
    - Publish to Slack
- Git tagging:
    manual: false
    final: false
    jobs:
    - Git Tagging


Build:
  key: BFM
  other:
    clean-working-dir: true
  tasks:
  - clean
  - checkout: !include common/checkout-default-repo.yaml
  - checkout:
      repository: sciter-adguard-mini-private
      path: adguard-mini-private
      force-clean-build: 'true'
      description: Checkout Repositories
  - checkout:
      repository: slack-scripts
      path: slack-scripts
      force-clean-build: 'true'
      description: Checkout Repositories
  - script:
      interpreter: SHELL
      file: bamboo-specs/scripts/prebuild_vars.sh
      working-dir: main
      description: Obtaining Prebuild Vars
  - inject-variables:
      file: main/build/vars.txt
      scope: RESULT
      namespace: inject
      description: Inject prebuild vars
  - script:
      interpreter: SHELL
      scripts:
      - ./bamboo-specs/scripts/configure.sh
      working-dir: main
      description: Configure
  - script:
      interpreter: SHELL
      scripts:
      - ./bamboo-specs/scripts/build.sh "${bamboo.build.config}"
      working-dir: main
      description: Build MAS app
  - inject-variables:
      file: main/build/MAS/version.txt
      scope: RESULT
      namespace: inject
      description: Inject Bamboo variables
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash

        set -e

        source .venv/bin/activate

        BUILD_DIR="../../build/${bamboo.build.config}"

        python -u Support/Scripts/changelog.py \
            --repo="SCITER/adguard-mini" \
            --gh-repo="AdguardTeam/AdGuardForSafari" \
            --output="$BUILD_DIR" \
            --channel="${bamboo.update.channel}" \
            --version="${bamboo.inject.base_version_name}" \
            --from=${bamboo.inject.tag_from}
      working-dir: main
      description: Create changelog
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash

        set -e

        bundle exec fastlane to_sentry config:${bamboo.build.config}
      working-dir: main
      description: Upload dSYMs to Sentry
  artifacts: !include build-for-publish-plans/artifacts-base.yaml
  requirements: !include common/build-requirements.yaml
  artifact-subscriptions: []
Publish to Slack:
  key: PTS
  tasks:
  - clean
  - checkout:
      repository: slack-scripts
      force-clean-build: 'true'
      description: Checkout Default Repository
  - checkout: !include common/checkout-default-repo.yaml
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        set -e
        ./main/bamboo-specs/scripts/publish_to_slack.sh "${PWD}/slack_kit.py" "${PWD}"
      description: Deploy to Slack
  requirements: !include common/build-requirements.yaml
  artifact-subscriptions:
  - artifact: !include common/app-archive-name.yaml
  - artifact: changelog.md

Git Tagging:
  key: GT
  other:
    clean-working-dir: true
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout Default Repository
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
      configuration:
        selectedRepository: defaultRepository
        tagName: v${bamboo.inject.version_name}
  artifact-subscriptions: []

variables:
  build.config: MAS
  changelog.tag.from: latest@tag
  update.channel: mas

repositories:
- sciter-adguard-mini:
    scope: global
- sciter-adguard-mini-private:
    scope: global
- slack-scripts:
    scope: global

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
- events:
  - plan-failed
  recipients:
  - webhook:
      name: Build webhook
      url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-mini-deploy
labels: []
other:
  concurrent-build-plugin: system-default
