# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

excluded:
    - "SciterResources/*"
    - "*/Localization/String+localized.swift"
    - "**/sp-flm"
    - "**/.build"

disabled_rules:
    - multiple_closures_with_trailing_closure
    - closure_parameter_position
    - todo
    - class_delegate_protocol
    - type_body_length
    - private_over_fileprivate
    - no_fallthrough_only

opt_in_rules:
    - accessibility_trait_for_button
    - unhandled_throwing_task
    - array_init
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - direct_return
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - explicit_init
    - fatal_error_message
    - first_where
    - flatmap_over_map_reduce
    - ibinspectable_in_extension
    - identical_operands
    - implicit_return
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - nimble_operator
    - number_separator
    - operator_usage_whitespace
    - overridden_super_call
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_action
    - private_outlet
    - private_subject
    - prohibited_super_call
    - reduce_into
    - redundant_nil_coalescing
    - required_enum_case
    - return_value_from_void_function
    - self_binding
    - shorthand_optional_binding
    - sorted_first_last
    - static_operator
    - strong_iboutlet
    - superfluous_else
    - test_case_accessibility
    - toggle_bool
    - trailing_closure
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - vertical_whitespace_opening_braces
    - vertical_whitespace_closing_braces
    - xct_specific_matcher
    - yoda_condition
    - weak_delegate
    - override_in_extension
    - period_spacing

inclusive_language:
    severity: error

analyzer_rules:
    - capture_variable
    - unused_declaration
    - unused_import
    - typesafe_array_init

for_where:
    allow_for_as_filter: true

function_body_length: 70
number_separator:
    minimum_length: 5
    minimum_fraction_length: 7
identifier_name:
    max_length:
      warning: 50
      error: 70
    min_length:
        warning: 2
        error: 2
    excluded:
        - ExtensionSafariApiProtocolId
type_name:
    excluded:
        - "`private`"
generic_type_name:
    max_length:
        warning: 25
line_length:
    warning: 120
    ignores_interpolated_strings: true
    ignores_urls: true
    ignores_comments: true
file_length:
    warning: 400
    error: 800

force_try:
    severity: error
colon:
    flexible_right_spacing: true
    apply_to_dictionaries: true

nesting:
  type_level: 3

custom_rules:
    no_nsrect:
        regex: '\bNSRect\b'
        match_kinds: typeidentifier
        message: 'Use CGRect instead of NSRect'
    no_nssize:
        regex: '\bNSSize\b'
        match_kinds: typeidentifier
        message: 'Use CGSize instead of NSSize'
    no_nspoint:
        regex: '\bNSPoint\b'
        match_kinds: typeidentifier
        message: 'Use CGPoint instead of NSPoint'
    swiftui_state_private:
        regex: '@(State|StateObject|ObservedObject|EnvironmentObject)\s+var'
        message: 'SwiftUI @State/@StateObject/@ObservedObject/@EnvironmentObject properties should be private'
    swiftui_environment_private:
        regex: '@Environment\(\\\.\w+\)\s+var'
        message: 'SwiftUI @Environment properties should be private'
    comments_capitalized_ignore_possible_code:
        name: "Capitalize First Word In Comment"
        regex: "(^ +// +(?!swiftlint)[a-z]+)"
        message: "The first word of a comment should be capitalized"
        severity: warning
    boolean_redundant_condition:
        name: "Redundant Boolean Condition"
        regex: "(== true)|(== false)|(!= true)|(!= false)"
        message: "Comparing a boolean to true is redundant (use `?? false` for optionals), and `!`-syntax is preferred over comparing to false."
        severity: warning
    boolean_return:
        name: "Boolean Return"
        regex: "\\? (true : false)|(false : true)"
        message: "It is redundant to return true or false for a boolean value. Instead return the value itself."
        severity: warning
    redundant_default_parameter:
        name: "Redundant Default Value"
        regex: "(present|dismiss)\\(\\V*, completion: nil\\)"
        message: "Specifying a parameter with it's default value is redundant. Remove parameter or change it's value."
        severity: warning
    todo_jira:
        name: "TODO without JIRA reference"
        regex: "(?i)(?=[^\\n]\\/\\/\\s*(TODO|TO DO|FIX|FIXME|FIX ME):)(?!.*[a-zA-Z]*\\-\\d+)[^\\n]*"
        message: "Do not add TODOs without a JIRA reference. Create new JIRA Task and add Issue Id (e.g. TIGER-777) to comment."
        severity: warning
    dbg_logging:
        name: "Using [DBG] logging"
        regex: "(?i)\\[DBG\\]"
        message: "Do not use [DBG] logging"
        severity: warning
    legacy_file_headers:
        name: "Legacy File Header Comments"
        regex: "^\\s*//\\s+(Created by|Copyright ©)"
        message: "Remove legacy 'Created by' or 'Copyright ©' header comments. Use SPDX format instead: '// SPDX-FileCopyrightText:' and '// SPDX-License-Identifier:'"
        severity: warning
