// SPDX-FileCopyrightText: AdGuard Software Limited
// SPDX-License-Identifier: GPL-3.0-or-later
//
//  String+localized.swift
//  Generated by generate_strings_tables
//

import AML

extension String.localized
{
    // MARK: -
    public enum base
    {

        /** `"Secure page"` */
        /** */
        /** Domain view - Item title "Secure page" */
        static public let item_title_secure_page : String = { .localized.string ("item_title_secure_page", in: "Localizable") }()

        /** `"Protection is off for this website as it may interfere with its operation"` */
        /** */
        /** Domain view - Domain Item hint "Protection is off for this domain" */
        static public let item_hint_domain_protection_off : String = { .localized.string ("item_hint_domain_protection_off", in: "Localizable") }()

        /** `"Protection"` */
        /** */
        /** Domain view - Item title "Protection" */
        static public let item_title_protection : String = { .localized.string ("item_title_protection", in: "Localizable") }()

        /** `"Some extensions are off"` */
        /** */
        /** Domain view - Item title "Some extensions are off" */
        static public let item_attention_title_extensions_off : String = { .localized.string ("item_attention_title_extensions_off", in: "Localizable") }()

        /** `"Fix it"` */
        /** */
        /** Domain view - Item button title "Fix it" */
        static public let item_attention_button_title_fix_it : String = { .localized.string ("item_attention_button_title_fix_it", in: "Localizable") }()

        /** `"Block element"` */
        /** */
        /** Domain view - Item title "Block element" */
        static public let item_title_block_element : String = { .localized.string ("item_title_block_element", in: "Localizable") }()

        /** `"Report an issue"` */
        /** */
        /** Domain view - Item title "Report an issue" */
        static public let item_title_report_an_issue : String = { .localized.string ("item_title_report_an_issue", in: "Localizable") }()

        /** `"Rate AdGuard Mini"` */
        /** */
        /** Domain view - Item title "Rate AdGuard Mini" */
        static public let item_title_rate_adguard_mini : String = { .localized.string ("item_title_rate_adguard_mini", in: "Localizable") }()

        /** `"Protection is disabled"` */
        /** */
        /** Info view - Title "Protection is disabled" */
        static public let info_title_protection_disabled : String = { .localized.string ("info_title_protection_disabled", in: "Localizable") }()

        /** `"Failed to enable protection"` */
        /** */
        /** Info view - Title "Failed to enable protection" */
        static public let info_title_failed_enable_protection : String = { .localized.string ("info_title_failed_enable_protection", in: "Localizable") }()

        /** `"Enable"` */
        /** */
        /** Info view - Button title "Enable" */
        static public let info_button_title_enable : String = { .localized.string ("info_button_title_enable", in: "Localizable") }()

        /** `"Enabling..."` */
        /** */
        /** Info view - Button title "Enabling..." */
        static public let info_button_title_enabling : String = { .localized.string ("info_button_title_enabling", in: "Localizable") }()

        /** `"AdGuard Mini is not launched"` */
        /** */
        /** Info view - Title "AdGuard Mini is not launched" */
        static public let info_title_main_app_not_running : String = { .localized.string ("info_title_main_app_not_running", in: "Localizable") }()

        /** `"Failed to launch AdGuard Mini"` */
        /** */
        /** Info view - Title "Failed to launch AdGuard Mini" */
        static public let info_title_failed_launch_main_app : String = { .localized.string ("info_title_failed_launch_main_app", in: "Localizable") }()

        /** `"Launch AdGuard Mini"` */
        /** */
        /** Info view - Button title "Launch AdGuard Mini" */
        static public let info_button_title_launch : String = { .localized.string ("info_button_title_launch", in: "Localizable") }()

        /** `"Launching..."` */
        /** */
        /** Info view - Button title "Launching..." */
        static public let info_button_title_launching : String = { .localized.string ("info_button_title_launching", in: "Localizable") }()

        /** `"Something went wrong"` */
        /** */
        /** Info view - Title "Something went wrong" */
        static public let info_title_something_went_wrong : String = { .localized.string ("info_title_something_went_wrong", in: "Localizable") }()

        /** `"Failed to restart AdGuard Mini"` */
        /** */
        /** Info view - Title "Failed to restart AdGuard Mini" */
        static public let info_title_failed_restart_main_app : String = { .localized.string ("info_title_failed_restart_main_app", in: "Localizable") }()

        /** `"Please restart the app or contact support"` */
        /** */
        /** Info view - Subtitle "Please restart the app or contact support" */
        static public let info_subtitle_restart_app : String = { .localized.string ("info_subtitle_restart_app", in: "Localizable") }()

        /** `"Restart AdGuard Mini"` */
        /** */
        /** Info view - Button title "Restart AdGuard Mini" */
        static public let info_button_title_restart : String = { .localized.string ("info_button_title_restart", in: "Localizable") }()

        /** `"Restarting..."` */
        /** */
        /** Info view - Button title "Launching..." */
        static public let info_button_title_restarting : String = { .localized.string ("info_button_title_restarting", in: "Localizable") }()

        /** `"Try again"` */
        /** */
        /** Info view - Common button title "Try again" */
        static public let info_common_button_title_try_again : String = { .localized.string ("info_common_button_title_try_again", in: "Localizable") }()

        /** `"Your data may be exposed"` */
        /** */
        /** Info view - Base common subtitle "Your data may be exposed" */
        static public let info_base_common_subtitle : String = { .localized.string ("info_base_common_subtitle", in: "Localizable") }()

        /** `"Please try again or contact support"` */
        /** */
        /** Info view - Common subtitle after an error occurs */
        static public let info_error_subtitle : String = { .localized.string ("info_error_subtitle", in: "Localizable") }()

        /** `"Set up your ad blocker"` */
        /** */
        /** Info view - Title "Set up your ad blocker" */
        static public let info_title_set_up_ad_blocker : String = { .localized.string ("info_title_set_up_ad_blocker", in: "Localizable") }()

        /** `"To get AdGuard Mini up and running properly, you’ll need to enable a few settings"` */
        /** */
        /** info_subtitle_set_up_ad_blocker
        Info view - Subtitle "To get AdGuard Mini up and running properly, you’ll need to enable a few settings" */
        static public let info_subtitle_set_up_ad_blocker : String = { .localized.string ("info_subtitle_set_up_ad_blocker", in: "Localizable") }()

        /** `"Open AdGuard Mini"` */
        /** */
        /** Info view - Button title "Open AdGuard Mini" */
        static public let info_button_title_open_main_app : String = { .localized.string ("info_button_title_open_main_app", in: "Localizable") }()

        /** `"Opening..."` */
        /** */
        /** Info view - Button title "Opening..." */
        static public let info_button_title_opening : String = { .localized.string ("info_button_title_opening", in: "Localizable") }()
    }
}
