#!/bin/sh

# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#  generateConfigConstants.sh
#  AdguardMini
#

if [ "$ACTION" == "clean" ]; then
    exit 0
fi

echo "CONFIG ${AGP_CONFIG_CONSTANTS_FILE}"
echo "Creating XC config Constants Header File: ${AGP_CONFIG_CONSTANTS_FILE}"
echo "// ===========================================================================" > "${AGP_CONFIG_CONSTANTS_FILE}"
echo "// AUTOGENERATED FILE" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "// FILE IS CREATED EVERY BUILD PROCESS" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "// CREATED BY SCRIPT '$(basename "$0")'" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "// ===========================================================================" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "// MARK: List of Constants" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "/// Special enum, allowing to access some configuration constants" >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "enum ${AGP_CONFIG_CONSTANTS_CONTAINER_NAME} {" >> "${AGP_CONFIG_CONSTANTS_FILE}"
/usr/bin/env | /usr/bin/sort | /usr/bin/sed -n -E -e 's/"/\\"/g' -e 's/^ *(AG_[_A-Za-z0-9]*) *= *(.*)/\tstatic let \1 = "\2"/p' >> "${AGP_CONFIG_CONSTANTS_FILE}"
echo "}" >> "${AGP_CONFIG_CONSTANTS_FILE}"
