#!/bin/sh

# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#  generateSensitiveBuildConstants.sh
#  AdguardMini
#

if [ "$ACTION" == "clean" ]; then
    exit 0
fi

TARGET_FILE=${AGP_SENSITIVE_CONFIG_CONSTANTS_FILE}

echo "CONFIG ${TARGET_FILE}"
echo "Creating XC config Constants Header File: ${TARGET_FILE}"
echo '// ===========================================================================
// AUTOGENERATED FILE
// FILE IS CREATED EVERY BUILD PROCESS
// CREATED BY SCRIPT '$(basename "$0")'
// ===========================================================================

// MARK: List of Constants

/// Special enum, allowing to access some sensitive configuration constants
enum '${AGP_SENSITIVE_CONFIG_CONSTANTS_CONTAINER_NAME}' {' > "${TARGET_FILE}"
/usr/bin/env | /usr/bin/sort | /usr/bin/sed -n -E -e 's/"/\\"/g' -e 's/^ *(SENS_[_A-Za-z0-9]*) *= *(.*)/\tstatic let \1 = "\2"/p' >> "${TARGET_FILE}"
echo "}" >> "${TARGET_FILE}"
