// SPDX-FileCopyrightText: AdGuard Software Limited
// SPDX-License-Identifier: GPL-3.0-or-later
//
//  String+localized.swift
//  Generated by generate_strings_tables
//

import AML

extension String.localized
{
    // MARK: -
    public enum base
    {

        /** `"AdGuard Mini"` */
        /** */
        /** Common - App displayed name. */
        static public let app_displayed_name : String = { .localized.string ("app_displayed_name", in: "Localizable") }()

        /** `"About AdGuard Mini"` */
        /** */
        /** App Menu - "About" title. */
        static public let app_menu_about_title : String = { .localized.string ("app_menu_about_title", in: "Localizable") }()

        /** `"Preferences..."` */
        /** */
        /** App Menu - "Preferences..." title. */
        static public let app_menu_preferences_title : String = { .localized.string ("app_menu_preferences_title", in: "Localizable") }()

        /** `"Hide AdGuard Mini"` */
        /** */
        /** App Menu - "Hide AdGuard Mini" title. */
        static public let app_menu_hide_title : String = { .localized.string ("app_menu_hide_title", in: "Localizable") }()

        /** `"Hide Others"` */
        /** */
        /** App Menu - "Hide Others" title. */
        static public let app_menu_hide_others_title : String = { .localized.string ("app_menu_hide_others_title", in: "Localizable") }()

        /** `"Show All"` */
        /** */
        /** App Menu - "Show All" title. */
        static public let app_menu_show_all_title : String = { .localized.string ("app_menu_show_all_title", in: "Localizable") }()

        /** `"Close"` */
        /** */
        /** App Menu - "Close" title. */
        static public let app_menu_close_title : String = { .localized.string ("app_menu_close_title", in: "Localizable") }()

        /** `"Quit AdGuard Mini"` */
        /** */
        /** App Menu - "Quit AdGuard Mini" title. */
        static public let app_menu_quit_title : String = { .localized.string ("app_menu_quit_title", in: "Localizable") }()

        /** `"Quit AdGuard Mini?"` */
        /** */
        /** Terminating app Alert - Message text "Quit AdGuard Mini?" */
        static public let terminate_app_alert_message_text : String = { .localized.string ("terminate_app_alert_message_text", in: "Localizable") }()

        /** `"To manage filtering and automatically check for filter updates, let AdGuard Mini run in the background"` */
        /** */
        /** Terminating app Alert - Informative text */
        static public let terminate_app_alert_informative_text : String = { .localized.string ("terminate_app_alert_informative_text", in: "Localizable") }()

        /** `"Run in background"` */
        /** */
        /** Terminating app Alert - Button title "Run in background" */
        static public let terminate_app_alert_button_title_run_in_background : String = { .localized.string ("terminate_app_alert_button_title_run_in_background", in: "Localizable") }()

        /** `"Quit"` */
        /** */
        /** Terminating app Alert - Button title "Quit" */
        static public let terminate_app_alert_button_title_quit : String = { .localized.string ("terminate_app_alert_button_title_quit", in: "Localizable") }()

        /** `"Don’t ask me again"` */
        /** */
        /** Terminating app Alert - Suppression Button title "Don’t ask me again" */
        static public let terminate_app_alert_suppression_button_title : String = { .localized.string ("terminate_app_alert_suppression_button_title", in: "Localizable") }()

        /** `"AdGuard Mini Component"` */
        /** */
        /** Name of the crashed application for title of the crash reporter */
        static public let crash_reporter_title_adguard_component : String = { .localized.string ("crash_reporter_title_adguard_component", in: "Localizable") }()

        /** `"Crash Reporter: %1$@ (%2$@)"` */
        /** */
        /** Crash Reporter UI (SFBCrashReporterWindowController) */
        static public let window_controller_crash_reporter : String = { .localized.string ("window_controller_crash_reporter", in: "Localizable") }()

        /** `"Restart"` */
        /** */
        /** Request user about restarting AdGuard Mini */
        static public let restart_button : String = { .localized.string ("restart_button", in: "Localizable") }()

        /** `"Quit"` */
        /** */
        /** Request user about restarting AdGuard Mini */
        static public let restarting_request_quit : String = { .localized.string ("restarting_request_quit", in: "Localizable") }()

        /** `"Restart AdGuard Mini"` */
        /** */
        /** Request user about restarting AdGuard Mini */
        static public let restarting_request_message_title : String = { .localized.string ("restarting_request_message_title", in: "Localizable") }()

        /** `"The settings were reset. Please restart AdGuard Mini to restore its functionality"` */
        /** */
        /** Request user about restarting AdGuard Mini */
        static public let restarting_request_message_text : String = { .localized.string ("restarting_request_message_text", in: "Localizable") }()

        /** `"Close"` */
        /** */
        /** Title on Close button in error message */
        static public let close_button : String = { .localized.string ("close_button", in: "Localizable") }()

        /** `"Reset"` */
        /** */
        /** Request user about resetting AdGuard Mini */
        static public let reset_setting_button : String = { .localized.string ("reset_setting_button", in: "Localizable") }()

        /** `"Reset AdGuard Mini settings?"` */
        /** */
        /** Request user about resetting AdGuard Mini */
        static public let reset_settings_message : String = { .localized.string ("reset_settings_message", in: "Localizable") }()

        /** `"All AdGuard Mini settings will be reset to their default values. Custom settings will be removed"` */
        /** */
        /** Request user about resetting AdGuard Mini */
        static public let reseting_settings_request : String = { .localized.string ("reseting_settings_request", in: "Localizable") }()

        /** `"Move AdGuard Mini to the Applications folder"` */
        /** */
        /** Notify the user that the application cannot be run from the current location. */
        static public let error_running_app : String = { .localized.string ("error_running_app", in: "Localizable") }()

        /** `"AdGuard Mini needs to be in the Applications folder to run.\nPlease move it there and try again"` */
        /** */
        /** Notify the user that the application should be moved to the Applications folder. */
        static public let error_running_app_message : String = { .localized.string ("error_running_app_message", in: "Localizable") }()
    }
}
