/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: AppInfo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum Channel {
    unknown = 0,
    standalone_nightly = 1,
    standalone_beta = 2,
    standalone_release = 3,
    app_store = 4
}
export class AppInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        version?: string;
        channel?: Channel;
        dependencies?: ThirdPartyDependency[];
        updateAvailable?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("version" in data && data.version != undefined) {
                this.version = data.version;
            }
            if ("channel" in data && data.channel != undefined) {
                this.channel = data.channel;
            }
            if ("dependencies" in data && data.dependencies != undefined) {
                this.dependencies = data.dependencies;
            }
            if ("updateAvailable" in data && data.updateAvailable != undefined) {
                this.updateAvailable = data.updateAvailable;
            }
        }
    }
    get version() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set version(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get channel() {
        return pb_1.Message.getFieldWithDefault(this, 2, Channel.unknown) as Channel;
    }
    set channel(value: Channel) {
        pb_1.Message.setField(this, 2, value);
    }
    get dependencies() {
        return pb_1.Message.getRepeatedWrapperField(this, ThirdPartyDependency, 3) as ThirdPartyDependency[];
    }
    set dependencies(value: ThirdPartyDependency[]) {
        pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get updateAvailable() {
        return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
    }
    set updateAvailable(value: boolean) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        version?: string;
        channel?: Channel;
        dependencies?: ReturnType<typeof ThirdPartyDependency.prototype.toObject>[];
        updateAvailable?: boolean;
    }): AppInfo {
        const message = new AppInfo({});
        if (data.version != null) {
            message.version = data.version;
        }
        if (data.channel != null) {
            message.channel = data.channel;
        }
        if (data.dependencies != null) {
            message.dependencies = data.dependencies.map(item => ThirdPartyDependency.fromObject(item));
        }
        if (data.updateAvailable != null) {
            message.updateAvailable = data.updateAvailable;
        }
        return message;
    }
    toObject() {
        const data: {
            version?: string;
            channel?: Channel;
            dependencies?: ReturnType<typeof ThirdPartyDependency.prototype.toObject>[];
            updateAvailable?: boolean;
        } = {};
        if (this.version != null) {
            data.version = this.version;
        }
        if (this.channel != null) {
            data.channel = this.channel;
        }
        if (this.dependencies != null) {
            data.dependencies = this.dependencies.map((item: ThirdPartyDependency) => item.toObject());
        }
        if (this.updateAvailable != null) {
            data.updateAvailable = this.updateAvailable;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.version.length)
            writer.writeString(1, this.version);
        if (this.channel != Channel.unknown)
            writer.writeEnum(2, this.channel);
        if (this.dependencies.length)
            writer.writeRepeatedMessage(3, this.dependencies, (item: ThirdPartyDependency) => item.serialize(writer));
        if (this.updateAvailable != false)
            writer.writeBool(4, this.updateAvailable);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AppInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AppInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.version = reader.readString();
                    break;
                case 2:
                    message.channel = reader.readEnum();
                    break;
                case 3:
                    reader.readMessage(message.dependencies, () => pb_1.Message.addToRepeatedWrapperField(message, 3, ThirdPartyDependency.deserialize(reader), ThirdPartyDependency));
                    break;
                case 4:
                    message.updateAvailable = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): AppInfo {
        return AppInfo.deserialize(bytes);
    }
}
export class ThirdPartyDependency extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        name?: string;
        version?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("version" in data && data.version != undefined) {
                this.version = data.version;
            }
        }
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get version() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set version(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        name?: string;
        version?: string;
    }): ThirdPartyDependency {
        const message = new ThirdPartyDependency({});
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.version != null) {
            message.version = data.version;
        }
        return message;
    }
    toObject() {
        const data: {
            name?: string;
            version?: string;
        } = {};
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.version != null) {
            data.version = this.version;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.name.length)
            writer.writeString(1, this.name);
        if (this.version.length)
            writer.writeString(2, this.version);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ThirdPartyDependency {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ThirdPartyDependency();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.name = reader.readString();
                    break;
                case 2:
                    message.version = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ThirdPartyDependency {
        return ThirdPartyDependency.deserialize(bytes);
    }
}
