/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: EnterActivationCodeResult.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Helpers";
import * as pb_1 from "google-protobuf";
export enum EnterActivationCodeResult {
    notExists = 0,
    expired = 1,
    maxComputersExceed = 2,
    blocked = 3,
    valid = 4
}
export class EnterActivationCodeResultMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        result?: EnterActivationCodeResult;
        error?: dependency_1.OptionalError;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("result" in data && data.result != undefined) {
                this.result = data.result;
            }
            if ("error" in data && data.error != undefined) {
                this.error = data.error;
            }
        }
    }
    get result() {
        return pb_1.Message.getFieldWithDefault(this, 1, EnterActivationCodeResult.notExists) as EnterActivationCodeResult;
    }
    set result(value: EnterActivationCodeResult) {
        pb_1.Message.setField(this, 1, value);
    }
    get error() {
        return pb_1.Message.getWrapperField(this, dependency_1.OptionalError, 2) as dependency_1.OptionalError;
    }
    set error(value: dependency_1.OptionalError) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_error() {
        return pb_1.Message.getField(this, 2) != null;
    }
    static fromObject(data: {
        result?: EnterActivationCodeResult;
        error?: ReturnType<typeof dependency_1.OptionalError.prototype.toObject>;
    }): EnterActivationCodeResultMessage {
        const message = new EnterActivationCodeResultMessage({});
        if (data.result != null) {
            message.result = data.result;
        }
        if (data.error != null) {
            message.error = dependency_1.OptionalError.fromObject(data.error);
        }
        return message;
    }
    toObject() {
        const data: {
            result?: EnterActivationCodeResult;
            error?: ReturnType<typeof dependency_1.OptionalError.prototype.toObject>;
        } = {};
        if (this.result != null) {
            data.result = this.result;
        }
        if (this.error != null) {
            data.error = this.error.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.result != EnterActivationCodeResult.notExists)
            writer.writeEnum(1, this.result);
        if (this.has_error)
            writer.writeMessage(2, this.error, () => this.error.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): EnterActivationCodeResultMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new EnterActivationCodeResultMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.result = reader.readEnum();
                    break;
                case 2:
                    reader.readMessage(message.error, () => message.error = dependency_1.OptionalError.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): EnterActivationCodeResultMessage {
        return EnterActivationCodeResultMessage.deserialize(bytes);
    }
}
