/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: Settings.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum ReleaseVariants {
    unknown = 0,
    MAS = 1,
    standAlone = 2
}
export enum ImportMode {
    unknown = 0,
    full = 1,
    withoutAnnoyance = 2,
    cancel = 3
}
export enum QuitReaction {
    unknown = 0,
    ask = 1,
    quit = 2,
    keepRunning = 3
}
export enum SafariExtensionType {
    general = 0,
    privacy = 1,
    security = 2,
    social = 3,
    other = 4,
    custom = 5,
    adguard_for_safari = 6
}
export enum SafariExtensionStatus {
    unknown = 0,
    ok = 1,
    loading = 2,
    disabled = 3,
    limit_exceeded = 4,
    converter_error = 5,
    safari_error = 6
}
export class Settings extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        launchOnStartup?: boolean;
        showInMenuBar?: boolean;
        hardwareAcceleration?: boolean;
        autoFiltersUpdate?: boolean;
        realTimeFiltersUpdate?: boolean;
        quitReaction?: QuitReaction;
        debugLogging?: boolean;
        releaseVariant?: ReleaseVariants;
        consentFiltersIds?: number[];
        language?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [9], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("launchOnStartup" in data && data.launchOnStartup != undefined) {
                this.launchOnStartup = data.launchOnStartup;
            }
            if ("showInMenuBar" in data && data.showInMenuBar != undefined) {
                this.showInMenuBar = data.showInMenuBar;
            }
            if ("hardwareAcceleration" in data && data.hardwareAcceleration != undefined) {
                this.hardwareAcceleration = data.hardwareAcceleration;
            }
            if ("autoFiltersUpdate" in data && data.autoFiltersUpdate != undefined) {
                this.autoFiltersUpdate = data.autoFiltersUpdate;
            }
            if ("realTimeFiltersUpdate" in data && data.realTimeFiltersUpdate != undefined) {
                this.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
            }
            if ("quitReaction" in data && data.quitReaction != undefined) {
                this.quitReaction = data.quitReaction;
            }
            if ("debugLogging" in data && data.debugLogging != undefined) {
                this.debugLogging = data.debugLogging;
            }
            if ("releaseVariant" in data && data.releaseVariant != undefined) {
                this.releaseVariant = data.releaseVariant;
            }
            if ("consentFiltersIds" in data && data.consentFiltersIds != undefined) {
                this.consentFiltersIds = data.consentFiltersIds;
            }
            if ("language" in data && data.language != undefined) {
                this.language = data.language;
            }
        }
    }
    get launchOnStartup() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set launchOnStartup(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get showInMenuBar() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set showInMenuBar(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    get hardwareAcceleration() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set hardwareAcceleration(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get autoFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
    }
    set autoFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 4, value);
    }
    get realTimeFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
    }
    set realTimeFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 5, value);
    }
    get quitReaction() {
        return pb_1.Message.getFieldWithDefault(this, 6, QuitReaction.unknown) as QuitReaction;
    }
    set quitReaction(value: QuitReaction) {
        pb_1.Message.setField(this, 6, value);
    }
    get debugLogging() {
        return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
    }
    set debugLogging(value: boolean) {
        pb_1.Message.setField(this, 7, value);
    }
    get releaseVariant() {
        return pb_1.Message.getFieldWithDefault(this, 8, ReleaseVariants.unknown) as ReleaseVariants;
    }
    set releaseVariant(value: ReleaseVariants) {
        pb_1.Message.setField(this, 8, value);
    }
    get consentFiltersIds() {
        return pb_1.Message.getFieldWithDefault(this, 9, []) as number[];
    }
    set consentFiltersIds(value: number[]) {
        pb_1.Message.setField(this, 9, value);
    }
    get language() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set language(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data: {
        launchOnStartup?: boolean;
        showInMenuBar?: boolean;
        hardwareAcceleration?: boolean;
        autoFiltersUpdate?: boolean;
        realTimeFiltersUpdate?: boolean;
        quitReaction?: QuitReaction;
        debugLogging?: boolean;
        releaseVariant?: ReleaseVariants;
        consentFiltersIds?: number[];
        language?: string;
    }): Settings {
        const message = new Settings({});
        if (data.launchOnStartup != null) {
            message.launchOnStartup = data.launchOnStartup;
        }
        if (data.showInMenuBar != null) {
            message.showInMenuBar = data.showInMenuBar;
        }
        if (data.hardwareAcceleration != null) {
            message.hardwareAcceleration = data.hardwareAcceleration;
        }
        if (data.autoFiltersUpdate != null) {
            message.autoFiltersUpdate = data.autoFiltersUpdate;
        }
        if (data.realTimeFiltersUpdate != null) {
            message.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
        }
        if (data.quitReaction != null) {
            message.quitReaction = data.quitReaction;
        }
        if (data.debugLogging != null) {
            message.debugLogging = data.debugLogging;
        }
        if (data.releaseVariant != null) {
            message.releaseVariant = data.releaseVariant;
        }
        if (data.consentFiltersIds != null) {
            message.consentFiltersIds = data.consentFiltersIds;
        }
        if (data.language != null) {
            message.language = data.language;
        }
        return message;
    }
    toObject() {
        const data: {
            launchOnStartup?: boolean;
            showInMenuBar?: boolean;
            hardwareAcceleration?: boolean;
            autoFiltersUpdate?: boolean;
            realTimeFiltersUpdate?: boolean;
            quitReaction?: QuitReaction;
            debugLogging?: boolean;
            releaseVariant?: ReleaseVariants;
            consentFiltersIds?: number[];
            language?: string;
        } = {};
        if (this.launchOnStartup != null) {
            data.launchOnStartup = this.launchOnStartup;
        }
        if (this.showInMenuBar != null) {
            data.showInMenuBar = this.showInMenuBar;
        }
        if (this.hardwareAcceleration != null) {
            data.hardwareAcceleration = this.hardwareAcceleration;
        }
        if (this.autoFiltersUpdate != null) {
            data.autoFiltersUpdate = this.autoFiltersUpdate;
        }
        if (this.realTimeFiltersUpdate != null) {
            data.realTimeFiltersUpdate = this.realTimeFiltersUpdate;
        }
        if (this.quitReaction != null) {
            data.quitReaction = this.quitReaction;
        }
        if (this.debugLogging != null) {
            data.debugLogging = this.debugLogging;
        }
        if (this.releaseVariant != null) {
            data.releaseVariant = this.releaseVariant;
        }
        if (this.consentFiltersIds != null) {
            data.consentFiltersIds = this.consentFiltersIds;
        }
        if (this.language != null) {
            data.language = this.language;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.launchOnStartup != false)
            writer.writeBool(1, this.launchOnStartup);
        if (this.showInMenuBar != false)
            writer.writeBool(2, this.showInMenuBar);
        if (this.hardwareAcceleration != false)
            writer.writeBool(3, this.hardwareAcceleration);
        if (this.autoFiltersUpdate != false)
            writer.writeBool(4, this.autoFiltersUpdate);
        if (this.realTimeFiltersUpdate != false)
            writer.writeBool(5, this.realTimeFiltersUpdate);
        if (this.quitReaction != QuitReaction.unknown)
            writer.writeEnum(6, this.quitReaction);
        if (this.debugLogging != false)
            writer.writeBool(7, this.debugLogging);
        if (this.releaseVariant != ReleaseVariants.unknown)
            writer.writeEnum(8, this.releaseVariant);
        if (this.consentFiltersIds.length)
            writer.writePackedInt32(9, this.consentFiltersIds);
        if (this.language.length)
            writer.writeString(10, this.language);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Settings {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Settings();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.launchOnStartup = reader.readBool();
                    break;
                case 2:
                    message.showInMenuBar = reader.readBool();
                    break;
                case 3:
                    message.hardwareAcceleration = reader.readBool();
                    break;
                case 4:
                    message.autoFiltersUpdate = reader.readBool();
                    break;
                case 5:
                    message.realTimeFiltersUpdate = reader.readBool();
                    break;
                case 6:
                    message.quitReaction = reader.readEnum();
                    break;
                case 7:
                    message.debugLogging = reader.readBool();
                    break;
                case 8:
                    message.releaseVariant = reader.readEnum();
                    break;
                case 9:
                    message.consentFiltersIds = reader.readPackedInt32();
                    break;
                case 10:
                    message.language = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Settings {
        return Settings.deserialize(bytes);
    }
}
export class UserConsent extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        filtersIds?: number[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("filtersIds" in data && data.filtersIds != undefined) {
                this.filtersIds = data.filtersIds;
            }
        }
    }
    get filtersIds() {
        return pb_1.Message.getFieldWithDefault(this, 1, []) as number[];
    }
    set filtersIds(value: number[]) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        filtersIds?: number[];
    }): UserConsent {
        const message = new UserConsent({});
        if (data.filtersIds != null) {
            message.filtersIds = data.filtersIds;
        }
        return message;
    }
    toObject() {
        const data: {
            filtersIds?: number[];
        } = {};
        if (this.filtersIds != null) {
            data.filtersIds = this.filtersIds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.filtersIds.length)
            writer.writePackedInt32(1, this.filtersIds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserConsent {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserConsent();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.filtersIds = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserConsent {
        return UserConsent.deserialize(bytes);
    }
}
export class ImportSettingsConfirmation extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        mode?: ImportMode;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("mode" in data && data.mode != undefined) {
                this.mode = data.mode;
            }
        }
    }
    get mode() {
        return pb_1.Message.getFieldWithDefault(this, 1, ImportMode.unknown) as ImportMode;
    }
    set mode(value: ImportMode) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        mode?: ImportMode;
    }): ImportSettingsConfirmation {
        const message = new ImportSettingsConfirmation({});
        if (data.mode != null) {
            message.mode = data.mode;
        }
        return message;
    }
    toObject() {
        const data: {
            mode?: ImportMode;
        } = {};
        if (this.mode != null) {
            data.mode = this.mode;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.mode != ImportMode.unknown)
            writer.writeEnum(1, this.mode);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ImportSettingsConfirmation {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImportSettingsConfirmation();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.mode = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ImportSettingsConfirmation {
        return ImportSettingsConfirmation.deserialize(bytes);
    }
}
export class ImportStatus extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        success?: boolean;
        filtersIds?: number[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
            if ("filtersIds" in data && data.filtersIds != undefined) {
                this.filtersIds = data.filtersIds;
            }
        }
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get filtersIds() {
        return pb_1.Message.getFieldWithDefault(this, 2, []) as number[];
    }
    set filtersIds(value: number[]) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        success?: boolean;
        filtersIds?: number[];
    }): ImportStatus {
        const message = new ImportStatus({});
        if (data.success != null) {
            message.success = data.success;
        }
        if (data.filtersIds != null) {
            message.filtersIds = data.filtersIds;
        }
        return message;
    }
    toObject() {
        const data: {
            success?: boolean;
            filtersIds?: number[];
        } = {};
        if (this.success != null) {
            data.success = this.success;
        }
        if (this.filtersIds != null) {
            data.filtersIds = this.filtersIds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.success != false)
            writer.writeBool(1, this.success);
        if (this.filtersIds.length)
            writer.writePackedInt32(2, this.filtersIds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ImportStatus {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImportStatus();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.success = reader.readBool();
                    break;
                case 2:
                    message.filtersIds = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ImportStatus {
        return ImportStatus.deserialize(bytes);
    }
}
export class GlobalSettings extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enabled?: boolean;
        allExtensionEnabled?: boolean;
        newVersionAvailable?: boolean;
        releaseVariant?: ReleaseVariants;
        language?: string;
        debugLogging?: boolean;
        recentlyMigrated?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
            if ("allExtensionEnabled" in data && data.allExtensionEnabled != undefined) {
                this.allExtensionEnabled = data.allExtensionEnabled;
            }
            if ("newVersionAvailable" in data && data.newVersionAvailable != undefined) {
                this.newVersionAvailable = data.newVersionAvailable;
            }
            if ("releaseVariant" in data && data.releaseVariant != undefined) {
                this.releaseVariant = data.releaseVariant;
            }
            if ("language" in data && data.language != undefined) {
                this.language = data.language;
            }
            if ("debugLogging" in data && data.debugLogging != undefined) {
                this.debugLogging = data.debugLogging;
            }
            if ("recentlyMigrated" in data && data.recentlyMigrated != undefined) {
                this.recentlyMigrated = data.recentlyMigrated;
            }
        }
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get allExtensionEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set allExtensionEnabled(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    get newVersionAvailable() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set newVersionAvailable(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get releaseVariant() {
        return pb_1.Message.getFieldWithDefault(this, 4, ReleaseVariants.unknown) as ReleaseVariants;
    }
    set releaseVariant(value: ReleaseVariants) {
        pb_1.Message.setField(this, 4, value);
    }
    get language() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set language(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get debugLogging() {
        return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
    }
    set debugLogging(value: boolean) {
        pb_1.Message.setField(this, 6, value);
    }
    get recentlyMigrated() {
        return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
    }
    set recentlyMigrated(value: boolean) {
        pb_1.Message.setField(this, 7, value);
    }
    static fromObject(data: {
        enabled?: boolean;
        allExtensionEnabled?: boolean;
        newVersionAvailable?: boolean;
        releaseVariant?: ReleaseVariants;
        language?: string;
        debugLogging?: boolean;
        recentlyMigrated?: boolean;
    }): GlobalSettings {
        const message = new GlobalSettings({});
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        if (data.allExtensionEnabled != null) {
            message.allExtensionEnabled = data.allExtensionEnabled;
        }
        if (data.newVersionAvailable != null) {
            message.newVersionAvailable = data.newVersionAvailable;
        }
        if (data.releaseVariant != null) {
            message.releaseVariant = data.releaseVariant;
        }
        if (data.language != null) {
            message.language = data.language;
        }
        if (data.debugLogging != null) {
            message.debugLogging = data.debugLogging;
        }
        if (data.recentlyMigrated != null) {
            message.recentlyMigrated = data.recentlyMigrated;
        }
        return message;
    }
    toObject() {
        const data: {
            enabled?: boolean;
            allExtensionEnabled?: boolean;
            newVersionAvailable?: boolean;
            releaseVariant?: ReleaseVariants;
            language?: string;
            debugLogging?: boolean;
            recentlyMigrated?: boolean;
        } = {};
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        if (this.allExtensionEnabled != null) {
            data.allExtensionEnabled = this.allExtensionEnabled;
        }
        if (this.newVersionAvailable != null) {
            data.newVersionAvailable = this.newVersionAvailable;
        }
        if (this.releaseVariant != null) {
            data.releaseVariant = this.releaseVariant;
        }
        if (this.language != null) {
            data.language = this.language;
        }
        if (this.debugLogging != null) {
            data.debugLogging = this.debugLogging;
        }
        if (this.recentlyMigrated != null) {
            data.recentlyMigrated = this.recentlyMigrated;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enabled != false)
            writer.writeBool(1, this.enabled);
        if (this.allExtensionEnabled != false)
            writer.writeBool(2, this.allExtensionEnabled);
        if (this.newVersionAvailable != false)
            writer.writeBool(3, this.newVersionAvailable);
        if (this.releaseVariant != ReleaseVariants.unknown)
            writer.writeEnum(4, this.releaseVariant);
        if (this.language.length)
            writer.writeString(5, this.language);
        if (this.debugLogging != false)
            writer.writeBool(6, this.debugLogging);
        if (this.recentlyMigrated != false)
            writer.writeBool(7, this.recentlyMigrated);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GlobalSettings {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GlobalSettings();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.enabled = reader.readBool();
                    break;
                case 2:
                    message.allExtensionEnabled = reader.readBool();
                    break;
                case 3:
                    message.newVersionAvailable = reader.readBool();
                    break;
                case 4:
                    message.releaseVariant = reader.readEnum();
                    break;
                case 5:
                    message.language = reader.readString();
                    break;
                case 6:
                    message.debugLogging = reader.readBool();
                    break;
                case 7:
                    message.recentlyMigrated = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GlobalSettings {
        return GlobalSettings.deserialize(bytes);
    }
}
export class UpdateQuitReactionMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        reaction?: QuitReaction;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("reaction" in data && data.reaction != undefined) {
                this.reaction = data.reaction;
            }
        }
    }
    get reaction() {
        return pb_1.Message.getFieldWithDefault(this, 1, QuitReaction.unknown) as QuitReaction;
    }
    set reaction(value: QuitReaction) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        reaction?: QuitReaction;
    }): UpdateQuitReactionMessage {
        const message = new UpdateQuitReactionMessage({});
        if (data.reaction != null) {
            message.reaction = data.reaction;
        }
        return message;
    }
    toObject() {
        const data: {
            reaction?: QuitReaction;
        } = {};
        if (this.reaction != null) {
            data.reaction = this.reaction;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.reaction != QuitReaction.unknown)
            writer.writeEnum(1, this.reaction);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateQuitReactionMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateQuitReactionMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.reaction = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UpdateQuitReactionMessage {
        return UpdateQuitReactionMessage.deserialize(bytes);
    }
}
export class SafariExtensions extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        general?: SafariExtension;
        privacy?: SafariExtension;
        social?: SafariExtension;
        security?: SafariExtension;
        other?: SafariExtension;
        custom?: SafariExtension;
        adguardForSafari?: SafariExtension;
        allExtensionsEnabled?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("general" in data && data.general != undefined) {
                this.general = data.general;
            }
            if ("privacy" in data && data.privacy != undefined) {
                this.privacy = data.privacy;
            }
            if ("social" in data && data.social != undefined) {
                this.social = data.social;
            }
            if ("security" in data && data.security != undefined) {
                this.security = data.security;
            }
            if ("other" in data && data.other != undefined) {
                this.other = data.other;
            }
            if ("custom" in data && data.custom != undefined) {
                this.custom = data.custom;
            }
            if ("adguardForSafari" in data && data.adguardForSafari != undefined) {
                this.adguardForSafari = data.adguardForSafari;
            }
            if ("allExtensionsEnabled" in data && data.allExtensionsEnabled != undefined) {
                this.allExtensionsEnabled = data.allExtensionsEnabled;
            }
        }
    }
    get general() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 1) as SafariExtension;
    }
    set general(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_general() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get privacy() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 2) as SafariExtension;
    }
    set privacy(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_privacy() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get social() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 3) as SafariExtension;
    }
    set social(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_social() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get security() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 4) as SafariExtension;
    }
    set security(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_security() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get other() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 5) as SafariExtension;
    }
    set other(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 5, value);
    }
    get has_other() {
        return pb_1.Message.getField(this, 5) != null;
    }
    get custom() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 6) as SafariExtension;
    }
    set custom(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 6, value);
    }
    get has_custom() {
        return pb_1.Message.getField(this, 6) != null;
    }
    get adguardForSafari() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 7) as SafariExtension;
    }
    set adguardForSafari(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 7, value);
    }
    get has_adguard_for_safari() {
        return pb_1.Message.getField(this, 7) != null;
    }
    get allExtensionsEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
    }
    set allExtensionsEnabled(value: boolean) {
        pb_1.Message.setField(this, 8, value);
    }
    static fromObject(data: {
        general?: ReturnType<typeof SafariExtension.prototype.toObject>;
        privacy?: ReturnType<typeof SafariExtension.prototype.toObject>;
        social?: ReturnType<typeof SafariExtension.prototype.toObject>;
        security?: ReturnType<typeof SafariExtension.prototype.toObject>;
        other?: ReturnType<typeof SafariExtension.prototype.toObject>;
        custom?: ReturnType<typeof SafariExtension.prototype.toObject>;
        adguardForSafari?: ReturnType<typeof SafariExtension.prototype.toObject>;
        allExtensionsEnabled?: boolean;
    }): SafariExtensions {
        const message = new SafariExtensions({});
        if (data.general != null) {
            message.general = SafariExtension.fromObject(data.general);
        }
        if (data.privacy != null) {
            message.privacy = SafariExtension.fromObject(data.privacy);
        }
        if (data.social != null) {
            message.social = SafariExtension.fromObject(data.social);
        }
        if (data.security != null) {
            message.security = SafariExtension.fromObject(data.security);
        }
        if (data.other != null) {
            message.other = SafariExtension.fromObject(data.other);
        }
        if (data.custom != null) {
            message.custom = SafariExtension.fromObject(data.custom);
        }
        if (data.adguardForSafari != null) {
            message.adguardForSafari = SafariExtension.fromObject(data.adguardForSafari);
        }
        if (data.allExtensionsEnabled != null) {
            message.allExtensionsEnabled = data.allExtensionsEnabled;
        }
        return message;
    }
    toObject() {
        const data: {
            general?: ReturnType<typeof SafariExtension.prototype.toObject>;
            privacy?: ReturnType<typeof SafariExtension.prototype.toObject>;
            social?: ReturnType<typeof SafariExtension.prototype.toObject>;
            security?: ReturnType<typeof SafariExtension.prototype.toObject>;
            other?: ReturnType<typeof SafariExtension.prototype.toObject>;
            custom?: ReturnType<typeof SafariExtension.prototype.toObject>;
            adguardForSafari?: ReturnType<typeof SafariExtension.prototype.toObject>;
            allExtensionsEnabled?: boolean;
        } = {};
        if (this.general != null) {
            data.general = this.general.toObject();
        }
        if (this.privacy != null) {
            data.privacy = this.privacy.toObject();
        }
        if (this.social != null) {
            data.social = this.social.toObject();
        }
        if (this.security != null) {
            data.security = this.security.toObject();
        }
        if (this.other != null) {
            data.other = this.other.toObject();
        }
        if (this.custom != null) {
            data.custom = this.custom.toObject();
        }
        if (this.adguardForSafari != null) {
            data.adguardForSafari = this.adguardForSafari.toObject();
        }
        if (this.allExtensionsEnabled != null) {
            data.allExtensionsEnabled = this.allExtensionsEnabled;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_general)
            writer.writeMessage(1, this.general, () => this.general.serialize(writer));
        if (this.has_privacy)
            writer.writeMessage(2, this.privacy, () => this.privacy.serialize(writer));
        if (this.has_social)
            writer.writeMessage(3, this.social, () => this.social.serialize(writer));
        if (this.has_security)
            writer.writeMessage(4, this.security, () => this.security.serialize(writer));
        if (this.has_other)
            writer.writeMessage(5, this.other, () => this.other.serialize(writer));
        if (this.has_custom)
            writer.writeMessage(6, this.custom, () => this.custom.serialize(writer));
        if (this.has_adguard_for_safari)
            writer.writeMessage(7, this.adguardForSafari, () => this.adguardForSafari.serialize(writer));
        if (this.allExtensionsEnabled != false)
            writer.writeBool(8, this.allExtensionsEnabled);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SafariExtensions {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SafariExtensions();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.general, () => message.general = SafariExtension.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.privacy, () => message.privacy = SafariExtension.deserialize(reader));
                    break;
                case 3:
                    reader.readMessage(message.social, () => message.social = SafariExtension.deserialize(reader));
                    break;
                case 4:
                    reader.readMessage(message.security, () => message.security = SafariExtension.deserialize(reader));
                    break;
                case 5:
                    reader.readMessage(message.other, () => message.other = SafariExtension.deserialize(reader));
                    break;
                case 6:
                    reader.readMessage(message.custom, () => message.custom = SafariExtension.deserialize(reader));
                    break;
                case 7:
                    reader.readMessage(message.adguardForSafari, () => message.adguardForSafari = SafariExtension.deserialize(reader));
                    break;
                case 8:
                    message.allExtensionsEnabled = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SafariExtensions {
        return SafariExtensions.deserialize(bytes);
    }
}
export class SafariExtension extends pb_1.Message {
    #one_of_decls: number[][] = [[6]];
    constructor(data?: any[] | ({
        id?: string;
        rulesEnabled?: number;
        rulesTotal?: number;
        status?: SafariExtensionStatus;
    } & (({
        safariError?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("rulesEnabled" in data && data.rulesEnabled != undefined) {
                this.rulesEnabled = data.rulesEnabled;
            }
            if ("rulesTotal" in data && data.rulesTotal != undefined) {
                this.rulesTotal = data.rulesTotal;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("safariError" in data && data.safariError != undefined) {
                this.safariError = data.safariError;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get rulesEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set rulesEnabled(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get rulesTotal() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set rulesTotal(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 4, SafariExtensionStatus.unknown) as SafariExtensionStatus;
    }
    set status(value: SafariExtensionStatus) {
        pb_1.Message.setField(this, 4, value);
    }
    get safariError() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set safariError(value: string) {
        pb_1.Message.setOneofField(this, 6, this.#one_of_decls[0], value);
    }
    get has_safari_error() {
        return pb_1.Message.getField(this, 6) != null;
    }
    get _safariError() {
        const cases: {
            [index: number]: "none" | "safariError";
        } = {
            0: "none",
            6: "safariError"
        };
        return cases[pb_1.Message.computeOneofCase(this, [6])];
    }
    static fromObject(data: {
        id?: string;
        rulesEnabled?: number;
        rulesTotal?: number;
        status?: SafariExtensionStatus;
        safariError?: string;
    }): SafariExtension {
        const message = new SafariExtension({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.rulesEnabled != null) {
            message.rulesEnabled = data.rulesEnabled;
        }
        if (data.rulesTotal != null) {
            message.rulesTotal = data.rulesTotal;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.safariError != null) {
            message.safariError = data.safariError;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            rulesEnabled?: number;
            rulesTotal?: number;
            status?: SafariExtensionStatus;
            safariError?: string;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.rulesEnabled != null) {
            data.rulesEnabled = this.rulesEnabled;
        }
        if (this.rulesTotal != null) {
            data.rulesTotal = this.rulesTotal;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.safariError != null) {
            data.safariError = this.safariError;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.rulesEnabled != 0)
            writer.writeInt32(2, this.rulesEnabled);
        if (this.rulesTotal != 0)
            writer.writeInt32(3, this.rulesTotal);
        if (this.status != SafariExtensionStatus.unknown)
            writer.writeEnum(4, this.status);
        if (this.has_safari_error)
            writer.writeString(6, this.safariError);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SafariExtension {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SafariExtension();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.rulesEnabled = reader.readInt32();
                    break;
                case 3:
                    message.rulesTotal = reader.readInt32();
                    break;
                case 4:
                    message.status = reader.readEnum();
                    break;
                case 6:
                    message.safariError = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SafariExtension {
        return SafariExtension.deserialize(bytes);
    }
}
export class SafariExtensionUpdate extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        type?: SafariExtensionType;
        state?: SafariExtension;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("type" in data && data.type != undefined) {
                this.type = data.type;
            }
            if ("state" in data && data.state != undefined) {
                this.state = data.state;
            }
        }
    }
    get type() {
        return pb_1.Message.getFieldWithDefault(this, 1, SafariExtensionType.general) as SafariExtensionType;
    }
    set type(value: SafariExtensionType) {
        pb_1.Message.setField(this, 1, value);
    }
    get state() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 2) as SafariExtension;
    }
    set state(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_state() {
        return pb_1.Message.getField(this, 2) != null;
    }
    static fromObject(data: {
        type?: SafariExtensionType;
        state?: ReturnType<typeof SafariExtension.prototype.toObject>;
    }): SafariExtensionUpdate {
        const message = new SafariExtensionUpdate({});
        if (data.type != null) {
            message.type = data.type;
        }
        if (data.state != null) {
            message.state = SafariExtension.fromObject(data.state);
        }
        return message;
    }
    toObject() {
        const data: {
            type?: SafariExtensionType;
            state?: ReturnType<typeof SafariExtension.prototype.toObject>;
        } = {};
        if (this.type != null) {
            data.type = this.type;
        }
        if (this.state != null) {
            data.state = this.state.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.type != SafariExtensionType.general)
            writer.writeEnum(1, this.type);
        if (this.has_state)
            writer.writeMessage(2, this.state, () => this.state.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SafariExtensionUpdate {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SafariExtensionUpdate();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.type = reader.readEnum();
                    break;
                case 2:
                    reader.readMessage(message.state, () => message.state = SafariExtension.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SafariExtensionUpdate {
        return SafariExtensionUpdate.deserialize(bytes);
    }
}
