/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Subscription.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum Subscription {
    monthly = 0,
    annual = 1,
    trial = 2,
    standalone = 3
}
export class SubscriptionMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        subscriptionType?: Subscription;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("subscriptionType" in data && data.subscriptionType != undefined) {
                this.subscriptionType = data.subscriptionType;
            }
        }
    }
    get subscriptionType() {
        return pb_1.Message.getFieldWithDefault(this, 1, Subscription.monthly) as Subscription;
    }
    set subscriptionType(value: Subscription) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        subscriptionType?: Subscription;
    }): SubscriptionMessage {
        const message = new SubscriptionMessage({});
        if (data.subscriptionType != null) {
            message.subscriptionType = data.subscriptionType;
        }
        return message;
    }
    toObject() {
        const data: {
            subscriptionType?: Subscription;
        } = {};
        if (this.subscriptionType != null) {
            data.subscriptionType = this.subscriptionType;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.subscriptionType != Subscription.monthly)
            writer.writeEnum(1, this.subscriptionType);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SubscriptionMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SubscriptionMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.subscriptionType = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SubscriptionMessage {
        return SubscriptionMessage.deserialize(bytes);
    }
}
