/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: SupportMessage.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class SupportMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        email?: string;
        message?: string;
        addLogs?: boolean;
        theme?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("email" in data && data.email != undefined) {
                this.email = data.email;
            }
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
            if ("addLogs" in data && data.addLogs != undefined) {
                this.addLogs = data.addLogs;
            }
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
        }
    }
    get email() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set email(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get addLogs() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set addLogs(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set theme(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        email?: string;
        message?: string;
        addLogs?: boolean;
        theme?: string;
    }): SupportMessage {
        const message = new SupportMessage({});
        if (data.email != null) {
            message.email = data.email;
        }
        if (data.message != null) {
            message.message = data.message;
        }
        if (data.addLogs != null) {
            message.addLogs = data.addLogs;
        }
        if (data.theme != null) {
            message.theme = data.theme;
        }
        return message;
    }
    toObject() {
        const data: {
            email?: string;
            message?: string;
            addLogs?: boolean;
            theme?: string;
        } = {};
        if (this.email != null) {
            data.email = this.email;
        }
        if (this.message != null) {
            data.message = this.message;
        }
        if (this.addLogs != null) {
            data.addLogs = this.addLogs;
        }
        if (this.theme != null) {
            data.theme = this.theme;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.email.length)
            writer.writeString(1, this.email);
        if (this.message.length)
            writer.writeString(2, this.message);
        if (this.addLogs != false)
            writer.writeBool(3, this.addLogs);
        if (this.theme.length)
            writer.writeString(4, this.theme);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SupportMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SupportMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.email = reader.readString();
                    break;
                case 2:
                    message.message = reader.readString();
                    break;
                case 3:
                    message.addLogs = reader.readBool();
                    break;
                case 4:
                    message.theme = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SupportMessage {
        return SupportMessage.deserialize(bytes);
    }
}
