/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: UserRules.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class UserRules extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enabled?: boolean;
        rules?: UserRule[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
            if ("rules" in data && data.rules != undefined) {
                this.rules = data.rules;
            }
        }
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get rules() {
        return pb_1.Message.getRepeatedWrapperField(this, UserRule, 2) as UserRule[];
    }
    set rules(value: UserRule[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    static fromObject(data: {
        enabled?: boolean;
        rules?: ReturnType<typeof UserRule.prototype.toObject>[];
    }): UserRules {
        const message = new UserRules({});
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        if (data.rules != null) {
            message.rules = data.rules.map(item => UserRule.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            enabled?: boolean;
            rules?: ReturnType<typeof UserRule.prototype.toObject>[];
        } = {};
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        if (this.rules != null) {
            data.rules = this.rules.map((item: UserRule) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enabled != false)
            writer.writeBool(1, this.enabled);
        if (this.rules.length)
            writer.writeRepeatedMessage(2, this.rules, (item: UserRule) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserRules {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserRules();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.enabled = reader.readBool();
                    break;
                case 2:
                    reader.readMessage(message.rules, () => pb_1.Message.addToRepeatedWrapperField(message, 2, UserRule.deserialize(reader), UserRule));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserRules {
        return UserRules.deserialize(bytes);
    }
}
export class UserRule extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        rule?: string;
        enabled?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("rule" in data && data.rule != undefined) {
                this.rule = data.rule;
            }
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
        }
    }
    get rule() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set rule(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        rule?: string;
        enabled?: boolean;
    }): UserRule {
        const message = new UserRule({});
        if (data.rule != null) {
            message.rule = data.rule;
        }
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        return message;
    }
    toObject() {
        const data: {
            rule?: string;
            enabled?: boolean;
        } = {};
        if (this.rule != null) {
            data.rule = this.rule;
        }
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.rule.length)
            writer.writeString(1, this.rule);
        if (this.enabled != false)
            writer.writeBool(2, this.enabled);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserRule {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserRule();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.rule = reader.readString();
                    break;
                case 2:
                    message.enabled = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserRule {
        return UserRule.deserialize(bytes);
    }
}
export class UserRulesCallbackState extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        rules?: UserRule[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("rules" in data && data.rules != undefined) {
                this.rules = data.rules;
            }
        }
    }
    get rules() {
        return pb_1.Message.getRepeatedWrapperField(this, UserRule, 1) as UserRule[];
    }
    set rules(value: UserRule[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        rules?: ReturnType<typeof UserRule.prototype.toObject>[];
    }): UserRulesCallbackState {
        const message = new UserRulesCallbackState({});
        if (data.rules != null) {
            message.rules = data.rules.map(item => UserRule.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            rules?: ReturnType<typeof UserRule.prototype.toObject>[];
        } = {};
        if (this.rules != null) {
            data.rules = this.rules.map((item: UserRule) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.rules.length)
            writer.writeRepeatedMessage(1, this.rules, (item: UserRule) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserRulesCallbackState {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserRulesCallbackState();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.rules, () => pb_1.Message.addToRepeatedWrapperField(message, 1, UserRule.deserialize(reader), UserRule));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserRulesCallbackState {
        return UserRulesCallbackState.deserialize(bytes);
    }
}
