# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: ADGMINIIBN
  name: Increment build number
stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment
Increment:
  key: INCR
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: "true"
    - script:
        description: Configure
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/configure.sh
    - script:
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/increment_version.sh "build"
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: "skip ci: Automatic increment build number"
          selectedRepository: defaultRepository
  requirements: !include common/build-requirements.yaml

variables:
  no_need_private_vars: true

branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
