# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

require 'pathname'
require 'tmpdir'

import 'Building'
import 'VCSWork'
import 'Testing'
import 'Deploying'
import 'Updating/Updating'
import 'Sparkle'
import 'Sentry'
import 'Sciter'

require 'fastlane_toolkit'
extend AG

ensure_bundle_exec

before_all do |lane, options|
  @is_bamboo = ENV['bamboo_agentId'] && true

  unless %i[
    increment_version
    build_version_file
    update_third_party_deps
  ].include?(lane)
    setup_fastlane_toolkit(@is_bamboo)
  end

  @config = options[:config] || ENV['CONFIGURATION']
  @scheme = ENV['SCHEME']

  @root_path = File.dirname(File.realpath(__dir__))
  @root_build_path = "#{@root_path}/build"
  @build_path = "#{@root_build_path}/#{@config}"
  @derived_data_path = "#{@build_path}/derived_data"
  @project_file = "#{@root_path}/AdguardMini/AdguardMini.xcodeproj"

  @build_settings = parse_build_settings(
    project: @project_file,
    scheme: @scheme,
    configuration: @config
  )

  DefaultUpdateConstants.root_path = @root_path
  DefaultUpdateConstants.project_path = @project_file
end

desc 'Create sensitive config'
lane :create_sens_config do |_options|
  config_path = "#{@root_path}/../adguard-mini-private/configuration/PrivateConfig.xcconfig"
  prefix = 'mac-mini'
  keys = [
    "sentry-dsn-#{prefix}",
    'backend-request-encryption-key',
    'backend-request-key',
    "#{prefix}-license-encryption-key"
  ]
  create_xcconfig(
    keys: keys,
    config_path: config_path
  )
end

ENV['FASTLANE_PROC'] = 'true'
