# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: ADGMINIRT
  name: Run tests
stages:
  - Base Stage:
      manual: false
      final: false
      jobs:
        - Run tests

Run tests:
  key: JOB1
  other:
    clean-working-dir: true
  tasks:
    - checkout: !include common/checkout-default-repo.yaml
    - checkout:
        description: Checkout Private Repository
        repository: sciter-adguard-mini-private
        path: adguard-mini-private
        force-clean-build: "true"
    - script:
        description: Configure
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/configure.sh
        working-dir: main
    - script:
        description: Run test plans
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/test.sh
        working-dir: main
    - test-parser:
        type: junit
        ignore-time: 'false'
        test-results: main/build/test-reports/*.junit
  requirements: !include common/build-requirements.yaml

repositories:
  - sciter-adguard-mini:
      scope: global
  - sciter-adguard-mini-private:
      scope: global

branches:
  create: for-pull-request
  delete:
    after-deleted-days: 1
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: AdGuardMini app - run tests
  link-to-jira: true
branch-overrides:
  - master:
      triggers: [] # Tests should not be run on the 'master' branch

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
