# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: ADGMINIBIAP
  name: Build for test IAP
stages:
  - Base Stage:
      manual: false
      final: false
      jobs:
        - Build MAS IAP app

Build MAS IAP app:
  key: BMASIAPA
  other:
    clean-working-dir: true
  tasks:
    - checkout: !include common/checkout-default-repo.yaml
    - checkout:
        description: Checkout Private Repository
        repository: sciter-adguard-mini-private
        path: adguard-mini-private
        force-clean-build: "true"
    - script:
        description: Configure
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/configure.sh
        working-dir: main
    - script:
        description: Build MAS IAP app
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/build.sh "MAS(IAP)"
        working-dir: main
    - script:
        description: Upload dSYMs to Sentry
        interpreter: SHELL
        scripts:
        - |-
          #!/bin/bash

          set -e

          bundle exec fastlane to_sentry config:"MAS(IAP)"
        working-dir: main
  artifacts:
    - name: !include common/app-archive-name.yaml
      location: main/build/MAS(IAP)
      pattern: !include common/app-archive-name.yaml
      shared: true
      required: true
    - name: !include common/app-xcarchive-name.yaml
      location: main/build/MAS(IAP)
      pattern: !include common/app-xcarchive-name.yaml
      shared: true
      required: true
    - name: BuildLogMAS(IAP).log
      location: main/build/MAS(IAP)/logs
      pattern: AdGuard Mini-AdguardMini.log
      shared: true
      required: true
  requirements: !include common/build-requirements.yaml

variables:
  build.notarize: true

repositories:
  - sciter-adguard-mini:
      scope: global
  - sciter-adguard-mini-private:
      scope: global

branches:
  create: for-pull-request
  delete:
    after-deleted-days: 1
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: Build for test IAP
  link-to-jira: true

triggers: []

notifications:
  - events:
      - plan-failed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-sciter-vcs
labels: []
other:
  concurrent-build-plugin: system-default
