# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: ADGMINIBC
  name: Build for check
stages:
  - Base Stage:
      manual: false
      final: false
      jobs:
        - Check swift packages
        - Build Standalone Release app
        - Build MAS app

Check swift packages:
  key: JOBCHSWP
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: "true"
    - script:
        description: Check the consistency of the Swift packages
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/setup_ssh.sh
          - ./bamboo-specs/scripts/check_swift_packages.sh
  requirements: !include common/build-requirements.yaml

Build Standalone Release app:
  key: JOBBSTRA
  other:
    clean-working-dir: true
  tasks:
    - checkout: !include common/checkout-default-repo.yaml
    - checkout:
        description: Checkout Private Repository
        repository: sciter-adguard-mini-private
        path: adguard-mini-private
        force-clean-build: "true"
    - script:
        description: Configure
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/configure.sh
        working-dir: main
    - script:
        description: Build Release app
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/build.sh "Release"
        working-dir: main
    - script:
        description: Upload dSYMs to Sentry
        interpreter: SHELL
        scripts:
        - |-
          #!/bin/bash

          set -e

          bundle exec fastlane to_sentry config:Release
        working-dir: main
  artifacts:
    - name: Release-${bamboo.internal.app.archive}
      location: main/build/Release
      pattern: !include common/app-archive-name.yaml
      shared: true
      required: true
    - name: Standalone-AdGuardMini.xcarchive.zip
      location: main/build/Release
      pattern: !include common/app-xcarchive-name.yaml
      shared: true
      required: true
    - name: BuildLog.log
      location: main/build/Release/logs
      pattern: AdGuard Mini-AdguardMini.log
      shared: true
      required: true
  requirements: !include common/build-requirements.yaml

Build MAS app:
  key: JOBBMA
  other:
    clean-working-dir: true
  tasks:
    - checkout: !include common/checkout-default-repo.yaml
    - checkout:
        description: Checkout Private Repository
        repository: sciter-adguard-mini-private
        path: adguard-mini-private
        force-clean-build: "true"
    - script:
        description: Configure
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/configure.sh
        working-dir: main
    - script:
        description: Build MAS app
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/build.sh "MAS"
        working-dir: main
    - script:
        description: Upload dSYMs to Sentry
        interpreter: SHELL
        scripts:
        - |-
          #!/bin/bash

          set -e

          bundle exec fastlane to_sentry config:MAS
        working-dir: main
  artifacts:
    - name: MAS-${bamboo.internal.app.archive}
      location: main/build/MAS
      pattern: !include common/app-archive-name.yaml
      shared: true
      required: true
    - name: MAS-AdGuardMini.xcarchive.zip
      location: main/build/MAS
      pattern: !include common/app-xcarchive-name.yaml
      shared: true
      required: true
    - name: BuildLogMAS.log
      location: main/build/MAS/logs
      pattern: AdGuard Mini-AdguardMini.log
      shared: true
      required: true
  requirements: !include common/build-requirements.yaml

variables:
  build.notarize: true
  internal.app.archive: !include 'common/app-archive-name.yaml'

repositories:
  - sciter-adguard-mini:
      scope: global
  - sciter-adguard-mini-private:
      scope: global

branches:
  create: for-pull-request
  delete:
    after-deleted-days: 1
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: Build for check
  link-to-jira: true
branch-overrides:
  - master:
      triggers: [] # Test builds should not be built on the 'master' branch

notifications:
  - events:
      - plan-failed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-sciter-vcs
labels: []
other:
  concurrent-build-plugin: system-default
