# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
plan:
  project-key: ADGMINI
  key: ADGMINIRREUSE
  name: Run reuse lint
stages:
  - Base Stage:
      manual: false
      final: false
      jobs:
        - Run reuse lint

Run reuse lint:
  key: JOB1
  other:
    clean-working-dir: true
  tasks:
    - checkout: !include common/checkout-default-repo.yaml
    - checkout:
        description: Checkout bitbucket-scripts Repository
        repository: bitbucket-scripts
        path: bitbucket-scripts
        force-clean-build: "true"
    - script:
        description: Run reuse lint and publish report
        interpreter: SHELL
        scripts:
          - ./bamboo-specs/scripts/create_and_deploy_reuse_report.sh "sciter" "adguard-mini" "${bamboo.planRepository.1.revision}" "${bamboo.secretToken}" "build" "../bitbucket-scripts/bitbucket-kit.py"
        working-dir: main
  requirements: !include common/build-requirements.yaml

repositories:
  - sciter-adguard-mini:
      scope: global
  - bitbucket-scripts:
      scope: global

branches:
  create: for-pull-request
  delete:
    after-deleted-days: 1
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: AdGuardMini app - run tests
  link-to-jira: true
branch-overrides:
  - master:
      triggers: [] # Reuse lint should not be run on the 'master' branch

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
