// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: AppStoreSubscription.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// AppStore subscription type
public enum AppStoreSubscription: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case monthly // = 0
  case annual // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .monthly
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .monthly
    case 1: self = .annual
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .monthly: return 0
    case .annual: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AppStoreSubscription] = [
    .monthly,
    .annual,
  ]

}

/// AppStore subscriptions error
public enum AppStoreSubscriptionsError: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case productsBanned // = 1
  case otherError // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .productsBanned
    case 2: self = .otherError
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .productsBanned: return 1
    case .otherError: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AppStoreSubscriptionsError] = [
    .unknown,
    .productsBanned,
    .otherError,
  ]

}

/// Describes AppStore Subscription
public struct AppStoreSubscriptionInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var subscriptionType: AppStoreSubscription = .monthly

  public var displayPrice: String = String()

  public var trialDays: Int32 = 0

  public var introOfferDisplayPrice: String {
    get {return _introOfferDisplayPrice ?? String()}
    set {_introOfferDisplayPrice = newValue}
  }
  /// Returns true if `introOfferDisplayPrice` has been explicitly set.
  public var hasIntroOfferDisplayPrice: Bool {return self._introOfferDisplayPrice != nil}
  /// Clears the value of `introOfferDisplayPrice`. Subsequent reads from it will return its default value.
  public mutating func clearIntroOfferDisplayPrice() {self._introOfferDisplayPrice = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _introOfferDisplayPrice: String? = nil
}

/// Additional promo info
public struct PromoInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String = String()

  public var subtitle: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// AppStore available subscriptions
public struct AppStoreSubscriptions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isTrialAvailable: Bool = false

  public var monthly: AppStoreSubscriptionInfo {
    get {return _monthly ?? AppStoreSubscriptionInfo()}
    set {_monthly = newValue}
  }
  /// Returns true if `monthly` has been explicitly set.
  public var hasMonthly: Bool {return self._monthly != nil}
  /// Clears the value of `monthly`. Subsequent reads from it will return its default value.
  public mutating func clearMonthly() {self._monthly = nil}

  public var annual: AppStoreSubscriptionInfo {
    get {return _annual ?? AppStoreSubscriptionInfo()}
    set {_annual = newValue}
  }
  /// Returns true if `annual` has been explicitly set.
  public var hasAnnual: Bool {return self._annual != nil}
  /// Clears the value of `annual`. Subsequent reads from it will return its default value.
  public mutating func clearAnnual() {self._annual = nil}

  public var promoInfo: PromoInfo {
    get {return _promoInfo ?? PromoInfo()}
    set {_promoInfo = newValue}
  }
  /// Returns true if `promoInfo` has been explicitly set.
  public var hasPromoInfo: Bool {return self._promoInfo != nil}
  /// Clears the value of `promoInfo`. Subsequent reads from it will return its default value.
  public mutating func clearPromoInfo() {self._promoInfo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _monthly: AppStoreSubscriptionInfo? = nil
  fileprivate var _annual: AppStoreSubscriptionInfo? = nil
  fileprivate var _promoInfo: PromoInfo? = nil
}

/// Defines AppStore subscriptions message
public struct AppStoreSubscriptionsMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var error: AppStoreSubscriptionsError = .unknown

  public var result: AppStoreSubscriptions {
    get {return _result ?? AppStoreSubscriptions()}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _result: AppStoreSubscriptions? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension AppStoreSubscription: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AppStoreSubscription_monthly\0\u{1}AppStoreSubscription_annual\0")
}

extension AppStoreSubscriptionsError: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AppStoreSubscriptionsError_unknown\0\u{1}AppStoreSubscriptionsError_products_banned\0\u{1}AppStoreSubscriptionsError_other_error\0")
}

extension AppStoreSubscriptionInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AppStoreSubscriptionInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_type\0\u{3}display_price\0\u{3}trial_days\0\u{3}intro_offer_display_price\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.subscriptionType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayPrice) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.trialDays) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._introOfferDisplayPrice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.subscriptionType != .monthly {
      try visitor.visitSingularEnumField(value: self.subscriptionType, fieldNumber: 1)
    }
    if !self.displayPrice.isEmpty {
      try visitor.visitSingularStringField(value: self.displayPrice, fieldNumber: 2)
    }
    if self.trialDays != 0 {
      try visitor.visitSingularInt32Field(value: self.trialDays, fieldNumber: 3)
    }
    try { if let v = self._introOfferDisplayPrice {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AppStoreSubscriptionInfo, rhs: AppStoreSubscriptionInfo) -> Bool {
    if lhs.subscriptionType != rhs.subscriptionType {return false}
    if lhs.displayPrice != rhs.displayPrice {return false}
    if lhs.trialDays != rhs.trialDays {return false}
    if lhs._introOfferDisplayPrice != rhs._introOfferDisplayPrice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PromoInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "PromoInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}subtitle\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.subtitle) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    if !self.subtitle.isEmpty {
      try visitor.visitSingularStringField(value: self.subtitle, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PromoInfo, rhs: PromoInfo) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs.subtitle != rhs.subtitle {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AppStoreSubscriptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AppStoreSubscriptions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_trial_available\0\u{1}monthly\0\u{1}annual\0\u{1}promoInfo\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isTrialAvailable) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._monthly) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._annual) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._promoInfo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.isTrialAvailable != false {
      try visitor.visitSingularBoolField(value: self.isTrialAvailable, fieldNumber: 1)
    }
    try { if let v = self._monthly {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._annual {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._promoInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AppStoreSubscriptions, rhs: AppStoreSubscriptions) -> Bool {
    if lhs.isTrialAvailable != rhs.isTrialAvailable {return false}
    if lhs._monthly != rhs._monthly {return false}
    if lhs._annual != rhs._annual {return false}
    if lhs._promoInfo != rhs._promoInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AppStoreSubscriptionsMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AppStoreSubscriptionsMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0\u{1}result\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.error) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._result) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.error != .unknown {
      try visitor.visitSingularEnumField(value: self.error, fieldNumber: 1)
    }
    try { if let v = self._result {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AppStoreSubscriptionsMessage, rhs: AppStoreSubscriptionsMessage) -> Bool {
    if lhs.error != rhs.error {return false}
    if lhs._result != rhs._result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
