// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: EnterActivationCodeResult.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// EnterActivationCodeResult type
public enum EnterActivationCodeResult: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case notExists // = 0
  case expired // = 1
  case maxComputersExceed // = 2
  case blocked // = 3
  case valid // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .notExists
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .notExists
    case 1: self = .expired
    case 2: self = .maxComputersExceed
    case 3: self = .blocked
    case 4: self = .valid
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .notExists: return 0
    case .expired: return 1
    case .maxComputersExceed: return 2
    case .blocked: return 3
    case .valid: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [EnterActivationCodeResult] = [
    .notExists,
    .expired,
    .maxComputersExceed,
    .blocked,
    .valid,
  ]

}

public struct EnterActivationCodeResultMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: EnterActivationCodeResult = .notExists

  public var error: OptionalError {
    get {return _error ?? OptionalError()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: OptionalError? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension EnterActivationCodeResult: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "EnterActivationCodeResult_notExists"),
    1: .same(proto: "EnterActivationCodeResult_expired"),
    2: .same(proto: "EnterActivationCodeResult_maxComputersExceed"),
    3: .same(proto: "EnterActivationCodeResult_blocked"),
    4: .same(proto: "EnterActivationCodeResult_valid"),
  ]
}

extension EnterActivationCodeResultMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "EnterActivationCodeResultMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.result) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.result != .notExists {
      try visitor.visitSingularEnumField(value: self.result, fieldNumber: 1)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: EnterActivationCodeResultMessage, rhs: EnterActivationCodeResultMessage) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
