// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: License.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum LicenseStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case active // = 1
  case trial // = 2
  case free // = 3
  case blockedAppID // = 4
  case expired // = 5
  case uninstall // = 6
  case wrongKey // = 7
  case alreadyActivate // = 8
  case blocked // = 9
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .active
    case 2: self = .trial
    case 3: self = .free
    case 4: self = .blockedAppID
    case 5: self = .expired
    case 6: self = .uninstall
    case 7: self = .wrongKey
    case 8: self = .alreadyActivate
    case 9: self = .blocked
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .active: return 1
    case .trial: return 2
    case .free: return 3
    case .blockedAppID: return 4
    case .expired: return 5
    case .uninstall: return 6
    case .wrongKey: return 7
    case .alreadyActivate: return 8
    case .blocked: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [LicenseStatus] = [
    .unknown,
    .active,
    .trial,
    .free,
    .blockedAppID,
    .expired,
    .uninstall,
    .wrongKey,
    .alreadyActivate,
    .blocked,
  ]

}

public enum LicenseType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case personal // = 1
  case family // = 2
  case standard // = 3
  case mobile // = 4
  case premium // = 5
  case beta // = 6
  case bonus // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .personal
    case 2: self = .family
    case 3: self = .standard
    case 4: self = .mobile
    case 5: self = .premium
    case 6: self = .beta
    case 7: self = .bonus
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .personal: return 1
    case .family: return 2
    case .standard: return 3
    case .mobile: return 4
    case .premium: return 5
    case .beta: return 6
    case .bonus: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [LicenseType] = [
    .unknown,
    .personal,
    .family,
    .standard,
    .mobile,
    .premium,
    .beta,
    .bonus,
  ]

}

public enum SubscriptionStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case active // = 1
  case pastDue // = 2
  case paused // = 3
  case deleted // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .active
    case 2: self = .pastDue
    case 3: self = .paused
    case 4: self = .deleted
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .active: return 1
    case .pastDue: return 2
    case .paused: return 3
    case .deleted: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SubscriptionStatus] = [
    .unknown,
    .active,
    .pastDue,
    .paused,
    .deleted,
  ]

}

public enum WebActivateResult: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case cancelled // = 1
  case userRedirectedToPurchase // = 2
  case success // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .cancelled
    case 2: self = .userRedirectedToPurchase
    case 3: self = .success
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .cancelled: return 1
    case .userRedirectedToPurchase: return 2
    case .success: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [WebActivateResult] = [
    .unknown,
    .cancelled,
    .userRedirectedToPurchase,
    .success,
  ]

}

/// Describes license or error response
public struct LicenseOrError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: LicenseOrError.OneOf_Result? = nil

  public var license: License {
    get {
      if case .license(let v)? = result {return v}
      return License()
    }
    set {result = .license(newValue)}
  }

  public var error: Bool {
    get {
      if case .error(let v)? = result {return v}
      return false
    }
    set {result = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Result: Equatable, Sendable {
    case license(License)
    case error(Bool)

  }

  public init() {}
}

/// Describes user license
public struct License: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var validUntil: Int64 = 0

  public var renewalDate: Int64 = 0

  public var licenseKey: String = String()

  public var currentDevices: Int32 = 0

  public var totalDevices: Int32 = 0

  public var status: LicenseStatus = .unknown

  public var type: LicenseType = .unknown

  public var subscriptionStatus: SubscriptionStatus = .unknown

  public var applicationKeyOwner: String = String()

  public var licenseLifetime: Bool = false

  public var licenseTrial: Bool = false

  public var appStoreSubscription: Bool = false

  public var canReset: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct WebActivateResultMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: WebActivateResult {
    get {return _result ?? .unknown}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  public var error: OptionalError {
    get {return _error ?? OptionalError()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _result: WebActivateResult? = nil
  fileprivate var _error: OptionalError? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension LicenseStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LicenseStatus_unknown"),
    1: .same(proto: "LicenseStatus_active"),
    2: .same(proto: "LicenseStatus_trial"),
    3: .same(proto: "LicenseStatus_free"),
    4: .same(proto: "LicenseStatus_blocked_app_id"),
    5: .same(proto: "LicenseStatus_expired"),
    6: .same(proto: "LicenseStatus_uninstall"),
    7: .same(proto: "LicenseStatus_wrong_key"),
    8: .same(proto: "LicenseStatus_already_activate"),
    9: .same(proto: "LicenseStatus_blocked"),
  ]
}

extension LicenseType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LicenseType_unknown"),
    1: .same(proto: "LicenseType_personal"),
    2: .same(proto: "LicenseType_family"),
    3: .same(proto: "LicenseType_standard"),
    4: .same(proto: "LicenseType_mobile"),
    5: .same(proto: "LicenseType_premium"),
    6: .same(proto: "LicenseType_beta"),
    7: .same(proto: "LicenseType_bonus"),
  ]
}

extension SubscriptionStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SubscriptionStatus_unknown"),
    1: .same(proto: "SubscriptionStatus_active"),
    2: .same(proto: "SubscriptionStatus_past_due"),
    3: .same(proto: "SubscriptionStatus_paused"),
    4: .same(proto: "SubscriptionStatus_deleted"),
  ]
}

extension WebActivateResult: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "WebActivateResult_unknown"),
    1: .same(proto: "WebActivateResult_cancelled"),
    2: .same(proto: "WebActivateResult_user_redirected_to_purchase"),
    3: .same(proto: "WebActivateResult_success"),
  ]
}

extension LicenseOrError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "LicenseOrError"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "license"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: License?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .license(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .license(v)
        }
      }()
      case 2: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .license?: try {
      guard case .license(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LicenseOrError, rhs: LicenseOrError) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension License: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "License"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "valid_until"),
    2: .standard(proto: "renewal_date"),
    3: .standard(proto: "license_key"),
    4: .standard(proto: "current_devices"),
    5: .standard(proto: "total_devices"),
    6: .same(proto: "status"),
    7: .same(proto: "type"),
    8: .standard(proto: "subscription_status"),
    9: .standard(proto: "application_key_owner"),
    10: .standard(proto: "license_lifetime"),
    11: .standard(proto: "license_trial"),
    12: .standard(proto: "app_store_subscription"),
    13: .standard(proto: "can_reset"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.validUntil) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.renewalDate) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.licenseKey) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.currentDevices) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.totalDevices) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.subscriptionStatus) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.applicationKeyOwner) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.licenseLifetime) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.licenseTrial) }()
      case 12: try { try decoder.decodeSingularBoolField(value: &self.appStoreSubscription) }()
      case 13: try { try decoder.decodeSingularBoolField(value: &self.canReset) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.validUntil != 0 {
      try visitor.visitSingularInt64Field(value: self.validUntil, fieldNumber: 1)
    }
    if self.renewalDate != 0 {
      try visitor.visitSingularInt64Field(value: self.renewalDate, fieldNumber: 2)
    }
    if !self.licenseKey.isEmpty {
      try visitor.visitSingularStringField(value: self.licenseKey, fieldNumber: 3)
    }
    if self.currentDevices != 0 {
      try visitor.visitSingularInt32Field(value: self.currentDevices, fieldNumber: 4)
    }
    if self.totalDevices != 0 {
      try visitor.visitSingularInt32Field(value: self.totalDevices, fieldNumber: 5)
    }
    if self.status != .unknown {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 6)
    }
    if self.type != .unknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 7)
    }
    if self.subscriptionStatus != .unknown {
      try visitor.visitSingularEnumField(value: self.subscriptionStatus, fieldNumber: 8)
    }
    if !self.applicationKeyOwner.isEmpty {
      try visitor.visitSingularStringField(value: self.applicationKeyOwner, fieldNumber: 9)
    }
    if self.licenseLifetime != false {
      try visitor.visitSingularBoolField(value: self.licenseLifetime, fieldNumber: 10)
    }
    if self.licenseTrial != false {
      try visitor.visitSingularBoolField(value: self.licenseTrial, fieldNumber: 11)
    }
    if self.appStoreSubscription != false {
      try visitor.visitSingularBoolField(value: self.appStoreSubscription, fieldNumber: 12)
    }
    if self.canReset != false {
      try visitor.visitSingularBoolField(value: self.canReset, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: License, rhs: License) -> Bool {
    if lhs.validUntil != rhs.validUntil {return false}
    if lhs.renewalDate != rhs.renewalDate {return false}
    if lhs.licenseKey != rhs.licenseKey {return false}
    if lhs.currentDevices != rhs.currentDevices {return false}
    if lhs.totalDevices != rhs.totalDevices {return false}
    if lhs.status != rhs.status {return false}
    if lhs.type != rhs.type {return false}
    if lhs.subscriptionStatus != rhs.subscriptionStatus {return false}
    if lhs.applicationKeyOwner != rhs.applicationKeyOwner {return false}
    if lhs.licenseLifetime != rhs.licenseLifetime {return false}
    if lhs.licenseTrial != rhs.licenseTrial {return false}
    if lhs.appStoreSubscription != rhs.appStoreSubscription {return false}
    if lhs.canReset != rhs.canReset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension WebActivateResultMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "WebActivateResultMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: WebActivateResultMessage, rhs: WebActivateResultMessage) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
