// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Subscription.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Subscription type
public enum Subscription: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case monthly // = 0
  case annual // = 1
  case trial // = 2
  case standalone // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .monthly
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .monthly
    case 1: self = .annual
    case 2: self = .trial
    case 3: self = .standalone
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .monthly: return 0
    case .annual: return 1
    case .trial: return 2
    case .standalone: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Subscription] = [
    .monthly,
    .annual,
    .trial,
    .standalone,
  ]

}

public struct SubscriptionMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var subscriptionType: Subscription = .monthly

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Subscription: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Subscription_monthly"),
    1: .same(proto: "Subscription_annual"),
    2: .same(proto: "Subscription_trial"),
    3: .same(proto: "Subscription_standalone"),
  ]
}

extension SubscriptionMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SubscriptionMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "subscription_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.subscriptionType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionType != .monthly {
      try visitor.visitSingularEnumField(value: self.subscriptionType, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SubscriptionMessage, rhs: SubscriptionMessage) -> Bool {
    if lhs.subscriptionType != rhs.subscriptionType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
