// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Telemetry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Pageview or custom event.
public struct TelemetryEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: TelemetryEvent.OneOf_Kind? = nil

  public var pageView: PageView {
    get {
      if case .pageView(let v)? = kind {return v}
      return PageView()
    }
    set {kind = .pageView(newValue)}
  }

  public var customEvent: CustomTelemetryEvent {
    get {
      if case .customEvent(let v)? = kind {return v}
      return CustomTelemetryEvent()
    }
    set {kind = .customEvent(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Kind: Equatable, Sendable {
    case pageView(PageView)
    case customEvent(CustomTelemetryEvent)

  }

  public init() {}
}

/// Page view. Special type of event, refers to page view.
public struct PageView: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of shown page
  public var name: String = String()

  /// Name of referer page
  public var refName: String {
    get {return _refName ?? String()}
    set {_refName = newValue}
  }
  /// Returns true if `refName` has been explicitly set.
  public var hasRefName: Bool {return self._refName != nil}
  /// Clears the value of `refName`. Subsequent reads from it will return its default value.
  public mutating func clearRefName() {self._refName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _refName: String? = nil
}

/// Custom event. Custom type of event.
public struct CustomTelemetryEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of custom event
  public var name: String = String()

  /// Name of page where custom event occurs
  public var refName: String = String()

  public var actionName: String {
    get {return _actionName ?? String()}
    set {_actionName = newValue}
  }
  /// Returns true if `actionName` has been explicitly set.
  public var hasActionName: Bool {return self._actionName != nil}
  /// Clears the value of `actionName`. Subsequent reads from it will return its default value.
  public mutating func clearActionName() {self._actionName = nil}

  public var labelName: String {
    get {return _labelName ?? String()}
    set {_labelName = newValue}
  }
  /// Returns true if `labelName` has been explicitly set.
  public var hasLabelName: Bool {return self._labelName != nil}
  /// Clears the value of `labelName`. Subsequent reads from it will return its default value.
  public mutating func clearLabelName() {self._labelName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _actionName: String? = nil
  fileprivate var _labelName: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension TelemetryEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "TelemetryEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}page_view\0\u{3}custom_event\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: PageView?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .pageView(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .pageView(v)
        }
      }()
      case 2: try {
        var v: CustomTelemetryEvent?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .customEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .customEvent(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .pageView?: try {
      guard case .pageView(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .customEvent?: try {
      guard case .customEvent(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: TelemetryEvent, rhs: TelemetryEvent) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PageView: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "PageView"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}ref_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._refName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._refName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PageView, rhs: PageView) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._refName != rhs._refName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CustomTelemetryEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "CustomTelemetryEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}ref_name\0\u{3}action_name\0\u{3}label_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.refName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._actionName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._labelName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.refName.isEmpty {
      try visitor.visitSingularStringField(value: self.refName, fieldNumber: 2)
    }
    try { if let v = self._actionName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._labelName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CustomTelemetryEvent, rhs: CustomTelemetryEvent) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.refName != rhs.refName {return false}
    if lhs._actionName != rhs._actionName {return false}
    if lhs._labelName != rhs._labelName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
